### ISSUE TITLE
CSS not working on GitHub pages link 

### ISSUE THREAD

**Issue by Tshileo** [Tshileo/grid-layout-with-flex-components#1]
Hi, @abhaysharma  CSS I applied on visual studio code is not showing on the GitHub pages link that I made how do I fix it

**Comment by abhaysharma** [comment]
@Tshileo there are two issues:
1. Folder name for CSS is uppercase but the path in the index.html has lowercase css
2. The path to the CSS file in the index.html needs to start with css/ and not /css/
